version: '3.4'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www
      - ./backend/docker-entry.sh:/etc/entrypoint.sh
    entrypoint: ["sh", "/etc/entrypoint.sh"]